<H1 align="center"> 0x05. Python - Exceptions </H1>

<p align="center">
   <a href="https://www.holbertonschool.com/co"><img src="https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_1440,w_720,f_auto,q_auto/79001/368330_619080.png" width="200" height="200"/></a>

<p align="center"> 
   <b>Holberton School Bogotá D.C</b>
                
----
<H3> General </H3>

    Why Python programming is awesome (don’t forget to tweet today, with the hashtag #pythoniscool :))
    What’s the difference between errors and exceptions
    What are exceptions and how to use them
    When do we need to use exceptions
    How to correctly handle an exception
    What’s the purpose of catching exceptions
    How to raise a builtin exception
    When do we need to implement a clean-up action after an exception


### Tasks:

| Name | Description                    |
| ------------- | ------------------------------ |
| `0-safe_print_list.py `      | function that prints x elements of a list.       |
| `1-safe_print_integer.py`   | function that prints an integer with "{:d}".format()     |
| `2-safe_print_list_integers.py`      | function that prints the first x elements of a list and only integers.       |
| `3-safe_print_division.py`      | function that divides 2 integers and prints the result.       |
| `4-list_division.py`      | function that divides element by element 2 lists.       |
| `5-raise_exception.py`      | function that raises a type exception.       |
| `6-raise_exception_msg.py`      | function that raises a name exception with a message.       |
| `100-safe_print_integer_err.py`      |  function that prints an integer.       |
| `101-safe_function.py`      |  function that executes a function safely.        |


## Author: 
### Julian Ramirez <julianramirezch1@gmail.com>
----
[![Twitter Follow](https://img.shields.io/twitter/follow/JulianR_30.svg?style=social&label=Follow)](https://twitter.com/JulianR_30)

2020
